newProject/urls.py
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.urls import path, reverse_lazy
from test_django import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('info/', views.show_info, name='info'),

    path('signup_login/', views.sign_up_log_in, name='signup_login'),
    path('register_worker/', views.register_worker, name='register_worker'),
    path('', views.index, name='home'),
    path('show_worker/<int:id_team>/<int:id_user>/addtask/', views.create, name='create'),
    path('show_worker/<int:id_team>/<int:id_user>/<int:number_task>/deletetask/',
         views.delete_task, name='delete_task'),
    path('tasks_home/', views.tasks_home, name='tasks_home'),
    path('logout/', LogoutView.as_view(next_page=reverse_lazy('home')), name='logout'),
    path('user_logout', views.logout_user, name='logout_user'),

    path('leaderfView/<str:name>/', views.show_team_ofProject, name='worker_ofProject'),
    path('leaderView/<str:name>/<int:id_team>/', views.show_workerFromTeam, name='worker_fromTeam'),
    path('leaderView/<int:id_team>/<int:id_user>/', views.show_worker, name='show_worker'),
    path('leaderWorkerView/<int:id_team>/<int:id_worker>/', views.worker_info, name='worker_info'),

    path(r'change/<int:id_worker>/<int:task_number>/<int:task_status>/(?P<date_control>\d{4}-\d{2}-\d{2}-\d{2}-\d{2})/',
         views.change, name='change'),

    # ajax url
    path('ajax/validate_username', views.validate_username, name='validate_username'),
    path('ajax/validate_email', views.validate_email, name='validate_email'),
    path('ajax/check_task_number/<int:id_worker>/', views.check_numberTask, name='check_task_number'),

]

test_django/forms.py
from datetime import date

from django.core.exceptions import ValidationError

from . import models
from .models import Task, IntegerRangeField
from django.forms import ModelForm, DateTimeInput, IntegerField, TextInput, DateInput, NumberInput

from django import forms
from bootstrap_datepicker_plus.widgets import DatePickerInput


# class TaskForm(ModelForm):
#     class Meta:
#         model = Task
#         fields = ['number', 'worker', 'project', 'task_status', 'date_control']
#
#         widgets = {
#             'number': TextInput(attrs={
#                 'class': 'form-control',
#                 'placeholder': 'Номер задания'
#             }),
#             'worker': TextInput(attrs={
#                 'class': 'form-control',
#                 'placeholder': 'Работник'
#             }),
#             'project': TextInput(attrs={
#                'class': 'form-control',
#                 'placeholder': 'Проект'
#             }),
#             # 'department': TextInput(attrs={
#             #     'class': 'form-control',
#             #     'placeholder': 'Department'
#             # }),
#             'task_status': TextInput(attrs={
#                 'class': 'form-control',
#                 'placeholder': 'Статус задания (1 - задание выполнено, 0 - задание не выполнено)'
#             }),
#             'date_control': DateTimeInput(attrs={
#                 'class': 'form-control',
#                 'placeholder': 'Дата и время сдачи'
#             }),
#         }
class TaskForm(forms.Form):
    number = forms.IntegerField(help_text="Введите номер задания", min_value=1)
    task_status = forms.IntegerField(
        help_text="Введите статус задания (1 - задание выполнено, 0 - задание не выполнено)", min_value=0, max_value=1)
    date_control = forms.DateField(help_text="Выберите дату сдачи задания", widget=DatePickerInput())



#
# """
#     def clean_date_control(self):
#         date_local = self.cleaned_data['date_control']
#         mark = self.cleaned_data['mark']
#         if date.today().day - date_local.day > 7 and mark == 7:
#             raise ValidationError("Вы уверены, что 7 баллов?")
#         return date_local
# """

from .models import Worker
from django.forms import ModelForm, TextInput, DateTimeInput, Textarea


class WorkerForm(forms.Form):
    name = forms.CharField(help_text="Введите имя")
    surname = forms.CharField(help_text="Введите фамилию")
    birth_date = forms.DateField(help_text="Выберите дату рождения", widget=DatePickerInput())
    team = forms.IntegerField(help_text="Введите номер команды")

    class Meta:
        model = Worker
        fields = ['name', 'surname', 'birth_date', 'team']

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% load django_bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    {% load static %}
    <link rel = "stylesheet" type="text/css" href="{% static 'css/show_info.css' %}"/>
</head>
<header>
    <nav class="navbar navbar-expand-lg" style="background-color: #B0E0E6">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">Личный кабинет</a>
            <form class="d-flex">
                <a href="{% url 'logout_user' %}" class="btn btn-danger" type="submit">Выход</a>
            </form>
        </div>
    </nav>
</header>
<body>
    {% block content %}
    {% endblock %}
</body>
</html>

templates/change.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Изменить</title>
</head>
<body style="background: #202020">
<script
  src="https://code.jquery.com/jquery-3.7.1.js"
  integrity="sha256-eKhayi8LEQwp4NKxN+CfCh+3qOVUtJn3QNZ0TciWLP4="
  crossorigin="anonymous"></script>
{% extends 'base.html' %}
{% load crispy_forms_filters %}
{% load  crispy_forms_tags %}
{% block content %}
    {{ form.media }}
<form method='post' class="mx-auto" style = "width: 500px; margin-top: 200px">
<h1 class="display-2 text-light text-center">Изменить</h1>
{% csrf_token %}
    <div class="row g-3">
        <div class="col">
            {{ form.number|as_crispy_field }}
    </div>
        <div class="col">
            {{ form.task_status|as_crispy_field }}
    </div>
    </div>
            {{ form.date_control|as_crispy_field }}
    <div class="text-center">
        <button type="submit" id="task_button" class="btn btn-info">Сохранить</button>
    </div>
</form>
    {% block javascript %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
<script>
    $(document).ready(function (){
        $('#id_number').keyup(function (){
            $.ajax(
                {
                    data: $(this).serialize(),
                    url: "{% url 'check_task_number' id_worker %}",
                    success:
                    function (response){
                       if ($('#numberError').length == 0)
                           $('#id_number').after('<div class="invalid-feedback d-block" id="numberError"></div>');

                        if (response.exist == true) {
                            $('#id_number').removeClass('is-valid').addClass('is-invalid');
                            $('#numberError').removeClass('valid-feedback').addClass('invalid-feedback').text("Задание с таким номером уже существует");
                            $('#task_button').prop('disabled', true);
                        } else {
                            $('#id_number').removeClass('is-invalid').addClass('is-valid');
                            $('#numberError').removeClass('invalid-feedback').addClass('valid-feedback').text("Задание можно добавить");
                            $('#task_button').prop('disabled', false);
                        }
                    },
                    error: function (response){
                        console.log(response.responseJSON.errors);
                    }
                });
            return false;
        });
    });
</script>
{% endblock javascript %}
{% endblock %}
</body>
</html>

templates/create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body style="background: #202020">
<script
  src="https://code.jquery.com/jquery-3.7.1.js"
  integrity="sha256-eKhayi8LEQwp4NKxN+CfCh+3qOVUtJn3QNZ0TciWLP4="
  crossorigin="anonymous"></script>
{% extends 'base.html' %}
{% load crispy_forms_filters %}
{% load  crispy_forms_tags %}
{% block content %}
    {{ form.media }}
<form method='post' class="mx-auto" style = "width: 500px; margin-top: 200px">
<h1 class="display-2 text-light text-center">Добавить задание</h1>
{% csrf_token %}
    <div class="row g-3">
        <div class="col">
            {{ form.number|as_crispy_field }}
    </div>
        <div class="col">
            {{ form.task_status|as_crispy_field }}
    </div>
    </div>
    {{ form.date_control|as_crispy_field }}
    <div class="text-center">
        <button type="submit" id="task_button" class="btn btn-info">Добавить задание</button>
    </div>
</form>
    {% block javascript %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
<script>
    $(document).ready(function (){
        $('#id_number').keyup(function (){
            $.ajax(
                {
                    data: $(this).serialize(),
                    url: "{% url 'check_task_number' id_worker %}",
                    success:
                    function (response){
                       if ($('#numberError').length == 0)
                           $('#id_number').after('<div class="invalid-feedback d-block" id="numberError"></div>');

                        if (response.exist == true) {
                            $('#id_number').removeClass('is-valid').addClass('is-invalid');
                            $('#numberError').removeClass('valid-feedback').addClass('invalid-feedback').text("Задание с таким номером уже существует");
                            $('#task_button').prop('disabled', true);
                        } else {
                            $('#id_number').removeClass('is-invalid').addClass('is-valid');
                            $('#numberError').removeClass('invalid-feedback').addClass('valid-feedback').text("Задание можно добавить");
                            $('#task_button').prop('disabled', false);
                        }
                    },
                    error: function (response){
                        console.log(response.responseJSON.errors);
                    }
                });
            return false;
        });
    });
</script>
{% endblock javascript %}
{% endblock %}
</body>
</html>

templates/index.html
{% extends 'layout.html' %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
    <div class="features">
        <h1>{{ title }}</h1>
        <p>Современные технологии достигли такого уровня, что убеждённость
            некоторых оппонентов однозначно фиксирует необходимость направлений
            прогрессивного развития. Вот вам яркий пример современных тенденций
            — сложившаяся структура организации не оставляет шанса для
            поставленных обществом задач.
            Также как постоянное информационно-пропагандистское обеспечение
            нашей деятельности создаёт необходимость включения в
            производственный план целого ряда внеочередных мероприятий
            с учётом комплекса как самодостаточных, так и внешне зависимых
            концептуальных решений.</p>
    </div>
{% endblock %}

templates/layout.html
{% load static %}
<!doctype html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css">
</head>
<body>
    <aside>
        <img>
        <span class="my_photo"></span>
        <h3>Навигация</h3>
        <ul>
            <a href="{% url 'home' %}"><li><i class="bi bi-house-door-fill"></i> Главная</li></a>
            <a href="{% url 'tasks_home' %}"><li><i class="bi bi-person-vcard-fill"></i> Задания</li></a>
            <a href="{% url 'signup_login' %}"><li><button class="btn btn-info"><i class="bi bi-plus-circle-fill"></i> Войти/зарегистрироваться</button></li></a>
{#            <a href="{% url 'create' %}"><li><button class="btn btn-info"><i class="bi bi-plus-circle-fill"></i> Добавить задание</button></li></a>#}
        </ul>
    </aside>
    <main>
        {% block content %}
        {% endblock %}
    </main>
</body>
</html>

templates/leaderInfo.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Информация о тимлиде</title>
</head>
<body>

</body>
</html>

templates/leaderViewProject.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% extends "base.html" %}
    {% load static %}
    <link rel = "stylesheet" type="text/css" href="{% static 'css/show_info.css' %}"/>
</head>
<body>
{% block content %}
    <div class = "container">
        <div class="mx-auto d-grid gap-2" style = "margin-top: 45vh; width: 500px">
           {% for worker in worker %}
               <a href="{% url '' %}"class="btn btn-primary" type="button">{{ worker.name }}</a>
            {% endfor %}
        </div>
    </div>
{% endblock %}
</body>
</html>

templates/leaderViewTeam.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% extends "base.html" %}
    {% load static %}
    <link rel = "stylesheet" type="text/css" href="{% static 'css/show_info.css' %}"/>
</head>
<body>
{% block content %}
    <div class = "container">
        <div class="mx-auto d-grid gap-2" style = "margin-top: 45vh; width: 500px">
           {% for team in team %}
               <a href="{% url "worker_fromTeam" name team.id %}" class="btn btn-primary" type="button" style="background: #31F1FF; color: black">{{ team }}</a>
            {% endfor %}
        </div>
    </div>
{% endblock %}
</body>
</html>

templates/notAccess.html
<!doctype html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Нет доступа!</title>
</head>
<body>
    <div>Вы не зарегистрированы</div>
</body>
</html>

templates/registerWorker.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% load django_bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/login_worker.css' %}">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <div class="login">
            <div class="form">
                 <h2>Введите данные, чтобы завершить регистрацию1</h2>
                <form method="post">
                    {% csrf_token %}
                    <input type="text" placeholder="Имя" name="name">
                    <input type="text" placeholder="Фамилия" name="surname">
                    <input type="number" placeholder="Номер команды" name="team">
                    <input type="date" placeholder="День рождения" name="birth_date">
                    <span>{{ error }}</span>
{#                    <button type="submit" class="btn btn-success">Сохранить</button>#}
                    <input type="submit" value="Сохранить" class="submit">
                </form>
            </div>
        </div>
    </header>
</body>
</html>

templates/signUpLogIn.html
<!DOCTYPE html>
<html lang="en" >
<head>
    <meta charset="UTF-8">
    <title>Регистрация/авторизация</title>
    {% load static %}
    {% load django_bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <link href="https://fonts.googleapis.com/css2?family=Jost:wght@500&display=swap" rel="stylesheet">
</head>
<body>
	<div class="main">  	
		<input type="checkbox" id="chk" aria-hidden="true">

			<div class="signup">
				<form method="post">
                    {% csrf_token %}
                        <label for="chk" aria-hidden="true">Регистрация</label>
                        <input type="text" id="input_username" name="create_user_name" placeholder="Имя" required="">
                        <input type="email" id="input_email" name="create_email" placeholder="Email" required="">
                        <input type="password" name="create_password" placeholder="Пароль" required="">
                        <button id="registr_button">Зарегистрироваться</button>
				</form>
			</div>

			<div class="login">
				<form method="post">
                    {% csrf_token %}
					<label for="chk" aria-hidden="true">Авторизация</label>
					<input type="email" name="email" placeholder="Email" required="">
					<input type="password" name="password" placeholder="Пароль" required="">
					<button>Войти</button>
				</form>
			</div>
	</div>
{% block javascript %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
<script>
    $(document).ready(function (){
        $('#input_username').keyup(function (){
            $.ajax(
                {
                    data: $(this).serialize(),
                    url: "{% url 'validate_username' %}",
                    success:
                    function (response){
                        if ($('#usernameError').length == 0)
                            $('#input_username').after('<div class="invalid-feedback d-block" id="usernameError" style="text-align: center;"></div>');
                        if (response.taken == true) {
                            $('#input_username').removeClass('is-valid').addClass('is-invalid');
                            $('#usernameError').removeClass('valid-feedback').addClass('invalid-feedback').text("Такое имя пользователя уже существует");
                            $('#registr_button').prop('disabled', true);
                        } else {
                            $('#input_username').removeClass('is-invalid').addClass('is-valid');
                            $('#usernameError').removeClass('invalid-feedback').addClass('valid-feedback').text("Такое имя пользователя доступно");
                            $('#registr_button').prop('disabled', false);
                        }
                    },
                    error: function (response){
                        console.log(response.responseJSON.errors);
                    }
                });
            return false;
        });
    $('#input_email').keyup(function () {
    $.ajax({
        data: $(this).serialize(),
        url: "{% url 'validate_email' %}",
        success: function (response) {
            if ($('#emailError').length == 0)
                $('#input_email').after('<div class="invalid-feedback d-block" id="emailError" style="text-align: center;"></div>');

            if (response.taken ==true) {
                $('#input_email').removeClass('is-valid').addClass('is-invalid');
                $('#emailError').removeClass('valid-feedback').addClass('invalid-feedback').text("Такой адрес электронной почты уже существует");
                $('#registr_button').prop('disabled', true);
            } else {
                $('#input_email').removeClass('is-invalid').addClass('is-valid');
                $('#emailError').removeClass('invalid-feedback').addClass('valid-feedback').text("Такой адрес электронной почты доступен");
                $('#registr_button').prop('disabled', false);
            }
        },
        error: function (response) {
            console.log(response.responseJSON.errors);
        }
    });
    return false;
});
});
</script>
{% endblock javascript %}
</body>
</html>

templates/tasks_home.html
{% extends 'layout.html' %}

{% block title %}Задания{% endblock %}

{% block content %}
    <div class="features">
        <h1>Задания</h1>

        {% if tasks %}
            {% for task in tasks %}
                <div class="alert alert-warning">
                    <h3>{{ task.worker }}</h3>
                    <p>{{ task.leader }}</p>
                    {{ task.date_control }}
                    Статус: {{ task.task_status }}
                </div>
            {% endfor %}
        {% else %}
            <p>У вас нет записей</p>
        {% endif %}
    </div>
{% endblock %}

templates/workerInfo.html
<!DOCTYPE html>
<html lang="ru">
    <head>
        <meta charset="UTF-8">
        <title>Информация о сотруднике</title>
        {% extends "base.html" %}

        {% load static %}
        <link rel = "stylesheet" type="text/css" href="{% static 'css/show_info.css' %}"/>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
    </head>
    <body>
        {% block content %}
            <div class="card">
              <div class="ds-top"></div>
              <div class="avatar-holder">
                <img src="https://www.gravatar.com/avatar/%7B%7B link_img }}?s=100&d=retro" alt="Albert Einstein">
              </div>
              <div class="name">
                {{ worker.first_name }} {{ worker.last_name }}
              </div>
              <div class="ds-info">
                <div class="ds pens">
                    <i class="bi bi-patch-check"></i><h6 title="Number of pens created by the user">Команда</h6>
                  <p>{{ worker.team }}</p>
                </div>
                <div class="ds projects">
                    <i class="bi bi-chat-square-heart"></i><h6 title="Number of pens created by the user">id пользователя</h6>
                    <p>{{ worker.id_user }}</p>
                </div>
                <div class="ds posts">
                  <i class="bi bi-people-fill"></i><h6 title="Number of pens created by the user">Дата рождения</h6>
                  <p>{{ worker.date_birth }}</p>
                </div>
              </div>

            <div class="title">Список заданий</div>

                <table class="table ds-skill" style="color: #fff">
              <thead>
                <tr style= "color: #31F1FF; animation: fadeIn 5s;">
                  <th scope="col" style= "text-align: center; width: 100px">Номер задания</th>
                  <th scope="col" style= "text-align: center">Статус</th>
                  <th scope="col" style= "text-align: center">Дата сдачи</th>
                </tr>
              </thead>
              <tbody>
                    {% for task in tasks %}
                        {% if task.task_status == 1 %}
                            <tr class="table-light">
                        {% elif task.task_status == 0 %}
                            <tr class="table-dark">
                        {% else %}
                            <tr>
                        {% endif %}
                                <th scope="row" style= "text-align: center">{{ task.number }}</th>
                                <td style= "text-align: center" >{{ task.task_status }}</td>
                                <td style= "text-align: center">{{ task.date_control }}</td>
                            </tr>
                    {% endfor %}
              </tbody>
            </table>
            </div>
        {% endblock %}
    </body>
</html>

templates/workerInfoFromLeader.html
<!DOCTYPE html>
<html lang="ru">
    <head>
        <meta charset="UTF-8">
        <title>Информация о сотруднике</title>
        {% extends "base.html" %}

        {% load static %}
        <link rel = "stylesheet" type="text/css" href="{% static 'css/show_info.css' %}"/>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
    </head>
    <body>
        {% block content %}
            <div class="card">
              <div class="ds-top"></div>
              <div class="avatar-holder">
                <img src="https://www.gravatar.com/avatar/%7B%7B link_img }}?s=100&d=retro" alt="Albert Einstein">
              </div>
              <div class="name">
                {{ worker.first_name }} {{ worker.last_name }}
              </div>
            <div class="task" style= "margin-top:260px; margin-left:250px">
                <a href="{% url 'create' worker.team_id worker.id_user_id %}" type="button" class="btn btn btn-light">Добавить задание</a>
            </div>
              <div class="ds-info">
                <div class="ds pens">
                    <i class="bi bi-patch-check"></i><h6 title="Number of pens created by the user">Команда</h6>
                  <p>{{ worker.team }}</p>
                </div>
                <div class="ds projects">
                    <i class="bi bi-chat-square-heart"></i><h6 title="Number of pens created by the user">id пользователя</h6>
                    <p>{{ worker.id_user }}</p>
                </div>
                <div class="ds posts">
                  <i class="bi bi-people-fill"></i><h6 title="Number of pens created by the user">Дата рождения</h6>
                  <p>{{ worker.date_birth }}</p>
                </div>
              </div>

            <div class="title">Список заданий</div>
                <table class="table ds-skill" style="color: #fff">
                    <thead>
                        <tr style= "color: #31F1FF; animation: fadeIn 5s;">
                          <th scope="col" style= "text-align: center; width: 100px">Номер задания</th>
                          <th scope="col" style= "text-align: center">Статус</th>
                          <th scope="col" style= "text-align: center">Дата сдачи</th>
                        </tr>
                      </thead>
                      <tbody>
                            {% for task in tasks %}
                                {% if task.task_status == 1 %}
                                    <tr class="table-light">
                                {% elif task.task_status == 0 %}
                                    <tr class="table-dark">
                                {% else %}
                                    <tr>
                                {% endif %}
                                        <th scope="row" style= "text-align: center">{{ task.number }}</th>
                                        <td style= "text-align: center" >{{ task.task_status }}</td>
                                        <td style= "text-align: center">{{ task.date_control }}</td>
                                        <td>
                                        <a href="{% url 'change' worker.id task.number task.task_status task.date_control %}" type="button" class="btn btn-success">Изменить</a>
                                        </td>
                                        <td>
                                        <a href="{% url 'delete_task' id_team worker.id_user_id task.number %}" type="button" class="btn btn-danger">Удалить</a>
                                        </td>
                                    </tr>
                            {% endfor %}
                      </tbody>
                </table>
            </div>
        {% endblock %}
    </body>
</html>